const setCodes = [
  {
    id: 1858,
    name: "TITANS",
    slug: "titans",
    type: "expansion",
    collectibleCount: 145,
    collectibleRevealedCount: 19,
    nonCollectibleCount: 133,
    nonCollectibleRevealedCount: 32,
  },
  {
    id: 1869,
    name: "Path of Arthas",
    slug: "path-of-arthas",
    type: "",
    collectibleCount: 26,
    collectibleRevealedCount: 26,
    nonCollectibleCount: 23,
    nonCollectibleRevealedCount: 4,
  },
  {
    id: 1809,
    name: "Festival of Legends",
    slug: "festival-of-legends",
    type: "expansion",
    collectibleCount: 145,
    collectibleRevealedCount: 145,
    nonCollectibleCount: 47,
    nonCollectibleRevealedCount: 44,
  },
  {
    id: 1776,
    name: "March of the Lich King",
    slug: "march-of-the-lich-king",
    type: "expansion",
    collectibleCount: 183,
    collectibleRevealedCount: 183,
    nonCollectibleCount: 133,
    nonCollectibleRevealedCount: 60,
  },
  {
    id: 1691,
    name: "Murder at Castle Nathria",
    slug: "murder-at-castle-nathria",
    type: "expansion",
    collectibleCount: 170,
    collectibleRevealedCount: 170,
    nonCollectibleCount: 125,
    nonCollectibleRevealedCount: 53,
  },
  {
    id: 1658,
    name: "Voyage to the Sunken City",
    slug: "voyage-to-the-sunken-city",
    type: "expansion",
    collectibleCount: 170,
    collectibleRevealedCount: 170,
    nonCollectibleCount: 520,
    nonCollectibleRevealedCount: 78,
  },
  {
    id: 1646,
    name: "Classic Cards",
    slug: "classic-cards",
    type: "",
    collectibleCount: 382,
    collectibleRevealedCount: 382,
    nonCollectibleCount: 96,
    nonCollectibleRevealedCount: 81,
  },
  {
    id: 1637,
    name: "Core",
    slug: "core",
    type: "",
    collectibleCount: 282,
    collectibleRevealedCount: 282,
    nonCollectibleCount: 59,
    nonCollectibleRevealedCount: 12,
  },
  {
    id: 1635,
    name: "Legacy",
    slug: "legacy",
    aliasSetIds: [3, 4],
    type: "",
    collectibleCount: 424,
    collectibleRevealedCount: 418,
    nonCollectibleCount: 167,
    nonCollectibleRevealedCount: 138,
  },
  {
    id: 1626,
    name: "Fractured in Alterac Valley",
    slug: "fractured-in-alterac-valley",
    type: "expansion",
    collectibleCount: 170,
    collectibleRevealedCount: 170,
    nonCollectibleCount: 378,
    nonCollectibleRevealedCount: 70,
  },
  {
    id: 1578,
    name: "United in Stormwind",
    slug: "united-in-stormwind",
    type: "expansion",
    collectibleCount: 170,
    collectibleRevealedCount: 170,
    nonCollectibleCount: 315,
    nonCollectibleRevealedCount: 66,
  },
  {
    id: 1525,
    name: "Forged in the Barrens",
    slug: "forged-in-the-barrens",
    type: "expansion",
    collectibleCount: 170,
    collectibleRevealedCount: 170,
    nonCollectibleCount: 667,
    nonCollectibleRevealedCount: 82,
  },
  {
    id: 1466,
    name: "Madness at the Darkmoon Faire",
    slug: "madness-at-the-darkmoon-faire",
    type: "expansion",
    collectibleCount: 170,
    collectibleRevealedCount: 170,
    nonCollectibleCount: 360,
    nonCollectibleRevealedCount: 111,
  },
  {
    id: 1443,
    name: "Scholomance Academy",
    slug: "scholomance-academy",
    type: "expansion",
    collectibleCount: 135,
    collectibleRevealedCount: 135,
    nonCollectibleCount: 197,
    nonCollectibleRevealedCount: 57,
  },
  {
    id: 1463,
    name: "Demon Hunter Initiate",
    slug: "demonhunter-initiate",
    type: "base",
    collectibleCount: 20,
    collectibleRevealedCount: 20,
    nonCollectibleCount: 6,
    nonCollectibleRevealedCount: 3,
  },
  {
    id: 1414,
    name: "Ashes of Outland",
    slug: "ashes-of-outland",
    type: "expansion",
    collectibleCount: 135,
    collectibleRevealedCount: 135,
    nonCollectibleCount: 84,
    nonCollectibleRevealedCount: 55,
  },
  {
    id: 1403,
    name: "Galakrond’s Awakening",
    slug: "galakronds-awakening",
    type: "adventure",
    collectibleCount: 35,
    collectibleRevealedCount: 35,
    nonCollectibleCount: 12,
    nonCollectibleRevealedCount: 5,
  },
  {
    id: 1347,
    name: "Descent of Dragons",
    slug: "descent-of-dragons",
    type: "expansion",
    collectibleCount: 140,
    collectibleRevealedCount: 140,
    nonCollectibleCount: 61,
    nonCollectibleRevealedCount: 56,
  },
  {
    id: 1158,
    name: "Saviors of Uldum",
    slug: "saviors-of-uldum",
    type: "expansion",
    collectibleCount: 135,
    collectibleRevealedCount: 135,
    nonCollectibleCount: 60,
    nonCollectibleRevealedCount: 47,
  },
  {
    id: 1130,
    name: "Rise of Shadows",
    slug: "rise-of-shadows",
    type: "expansion",
    collectibleCount: 136,
    collectibleRevealedCount: 136,
    nonCollectibleCount: 69,
    nonCollectibleRevealedCount: 54,
  },
  {
    id: 1129,
    name: "Rastakhan’s Rumble",
    slug: "rastakhans-rumble",
    type: "expansion",
    collectibleCount: 135,
    collectibleRevealedCount: 135,
    nonCollectibleCount: 31,
    nonCollectibleRevealedCount: 29,
  },
  {
    id: 1127,
    name: "The Boomsday Project",
    slug: "the-boomsday-project",
    type: "expansion",
    collectibleCount: 136,
    collectibleRevealedCount: 136,
    nonCollectibleCount: 32,
    nonCollectibleRevealedCount: 27,
  },
  {
    id: 1125,
    name: "The Witchwood",
    slug: "the-witchwood",
    type: "expansion",
    collectibleCount: 135,
    collectibleRevealedCount: 135,
    nonCollectibleCount: 41,
    nonCollectibleRevealedCount: 35,
  },
  {
    id: 1004,
    name: "Kobolds and Catacombs",
    slug: "kobolds-and-catacombs",
    type: "expansion",
    collectibleCount: 135,
    collectibleRevealedCount: 135,
    nonCollectibleCount: 108,
    nonCollectibleRevealedCount: 98,
  },
  {
    id: 1001,
    name: "Knights of the Frozen Throne",
    slug: "knights-of-the-frozen-throne",
    type: "expansion",
    collectibleCount: 135,
    collectibleRevealedCount: 135,
    nonCollectibleCount: 126,
    nonCollectibleRevealedCount: 53,
  },
  {
    id: 27,
    name: "Journey to Un’Goro",
    slug: "journey-to-ungoro",
    type: "expansion",
    collectibleCount: 135,
    collectibleRevealedCount: 135,
    nonCollectibleCount: 58,
    nonCollectibleRevealedCount: 56,
  },
  {
    id: 25,
    name: "Mean Streets of Gadgetzan",
    slug: "mean-streets-of-gadgetzan",
    type: "expansion",
    collectibleCount: 132,
    collectibleRevealedCount: 132,
    nonCollectibleCount: 95,
    nonCollectibleRevealedCount: 88,
  },
  {
    id: 23,
    name: "One Night in Karazhan",
    slug: "one-night-in-karazhan",
    type: "adventure",
    collectibleCount: 45,
    collectibleRevealedCount: 45,
    nonCollectibleCount: 55,
    nonCollectibleRevealedCount: 53,
  },
  {
    id: 21,
    name: "Whispers of the Old Gods",
    slug: "whispers-of-the-old-gods",
    type: "expansion",
    collectibleCount: 134,
    collectibleRevealedCount: 134,
    nonCollectibleCount: 39,
    nonCollectibleRevealedCount: 31,
  },
  {
    id: 20,
    name: "League of Explorers",
    slug: "league-of-explorers",
    type: "adventure",
    collectibleCount: 45,
    collectibleRevealedCount: 45,
    nonCollectibleCount: 188,
    nonCollectibleRevealedCount: 18,
  },
  {
    id: 15,
    name: "The Grand Tournament",
    slug: "the-grand-tournament",
    type: "expansion",
    collectibleCount: 132,
    collectibleRevealedCount: 132,
    nonCollectibleCount: 27,
    nonCollectibleRevealedCount: 20,
  },
  {
    id: 14,
    name: "Blackrock Mountain",
    slug: "blackrock-mountain",
    type: "adventure",
    collectibleCount: 31,
    collectibleRevealedCount: 31,
    nonCollectibleCount: 175,
    nonCollectibleRevealedCount: 10,
  },
  {
    id: 13,
    name: "Goblins vs Gnomes",
    slug: "goblins-vs-gnomes",
    type: "expansion",
    collectibleCount: 123,
    collectibleRevealedCount: 123,
    nonCollectibleCount: 32,
    nonCollectibleRevealedCount: 26,
  },
  {
    id: 12,
    name: "Curse of Naxxramas",
    slug: "naxxramas",
    type: "adventure",
    collectibleCount: 30,
    collectibleRevealedCount: 30,
    nonCollectibleCount: 118,
    nonCollectibleRevealedCount: 114,
  },
];

export default setCodes;
