export const setArray = {
  sets: [
    { name: "Naxxramas" },
    { name: "Goblins vs Gnomes" },
    { name: "Blackrock Mountain" },
    { name: "The Grand Tournament" },
    { name: "The League of Explorers" },
    { name: "Whispers of the Old Gods" },
    { name: "One Night in Karazhan" },
    { name: "Mean Streets of Gadgetzan" },
    { name: "Journey to Un'Goro" },
    { name: "Knights of the Frozen Throne" },
    { name: "Kobolds & Catacombs" },
    { name: "The Witchwood" },
    { name: "The Boomsday Project" },
    { name: "Rastakhan's Rumble" },
    { name: "Rise of Shadows" },
    { name: "Saviors of Uldum" },
    { name: "Descent of Dragons" },
    { name: "Galakrond's Awakening" },
    { name: "Ashes of Outland" },
    { name: "Scholomance Academy" },
    { name: "Demon Hunter Initiate" },
    { name: "Madness at the Darkmoon Faire" },
    { name: "Forged in the Barrens" },
    { name: "Legacy" },
    { name: "Core" },
    { name: "Classic" },
    { name: "Wailing Caverns" },
    { name: "United in Stormwind" },
    { name: "Fractured in Alterac Valley" },
    { name: "Voyage to the Sunken City" },
    { name: "Murder at Castle Nathria" },
  ],
};
