import naxxramas from "./images/set-logos/naxxramas.svg";

export const setArray = [
  {
    name: "Naxxramas",
    logo: naxxramas,
  },
  {
    name: "Goblins vs Gnomes",
    logo: "",
  },
  { name: "Blackrock Mountain", logo: "" },
  { name: "The Grand Tournament", logo: "" },
  { name: "The League of Explorers", logo: "" },
  { name: "Whispers of the Old Gods", logo: "" },
  { name: "One Night in Karazhan", logo: "" },
  { name: "Mean Streets of Gadgetzan", logo: "" },
  { name: "Journey to Un'Goro", logo: "" },
  { name: "Knights of the Frozen Throne", logo: "" },
  { name: "Kobolds & Catacombs", logo: "" },
  { name: "The Witchwood", logo: "" },
  { name: "The Boomsday Project", logo: "" },
  { name: "Rastakhan's Rumble", logo: "" },
  { name: "Rise of Shadows", logo: "" },
  { name: "Saviors of Uldum", logo: "" },
  { name: "Descent of Dragons", logo: "" },
  { name: "Galakrond's Awakening", logo: "" },
  { name: "Ashes of Outland", logo: "" },
  { name: "Scholomance Academy", logo: "" },
  { name: "Demon Hunter Initiate", logo: "" },
  { name: "Madness at the Darkmoon Faire", logo: "" },
  { name: "Forged in the Barrens", logo: "" },
  { name: "Legacy", logo: "" },
  { name: "Core", logo: "" },
  { name: "Classic", logo: "" },
  { name: "Wailing Caverns", logo: "" },
  { name: "United in Stormwind", logo: "" },
  { name: "Fractured in Alterac Valley", logo: "" },
  { name: "Voyage to the Sunken City", logo: "" },
  { name: "Murder at Castle Nathria", logo: "" },
];
