export const setArray = [
  {
    name: "Naxxramas",
    logo: "/set-logos/naxxramas.svg",
  },
  {
    name: "Goblins vs Gnomes",
    logo: "/set-logos/gvg.svg",
  },
  { name: "Blackrock Mountain", logo: "/set-logos/blackrock.svg" },
  { name: "The Grand Tournament", logo: "/set-logos/tournament.svg" },
  { name: "The League of Explorers", logo: "/set-logos/explorers.svg" },
  { name: "Whispers of the Old Gods", logo: "/set-logos/whispers.svg" },
  { name: "One Night in Karazhan", logo: "/set-logos/karazhan.svg" },
  { name: "Mean Streets of Gadgetzan", logo: "/set-logos/gadgetzan.svg" },
  { name: "Journey to Un'Goro", logo: "/set-logos/ungoro.svg" },
  { name: "Knights of the Frozen Throne", logo: "/set-logos/knights.svg" },
  { name: "Kobolds & Catacombs", logo: "/set-logos/kobolds.svg" },
  { name: "The Witchwood", logo: "/set-logos/witchwood.svg" },
  { name: "The Boomsday Project", logo: "/set-logos/boomsday.svg" },
  { name: "Rastakhan's Rumble", logo: "/set-logos/rumble.svg" },
  { name: "Rise of Shadows", logo: "/set-logos/shadows.svg" },
  { name: "Saviors of Uldum", logo: "/set-logos/uldum.svg" },
  { name: "Descent of Dragons", logo: "/set-logos/descent.svg" },
  { name: "Galakrond's Awakening", logo: "/set-logos/galakrond.svg" },
  { name: "Ashes of Outland", logo: "/set-logos/outland.svg" },
  { name: "Scholomance Academy", logo: "/set-logos/scholomance.svg" },
  { name: "Demon Hunter Initiate", logo: "/set-logos/demonhunter.svg" },
  { name: "Madness at the Darkmoon Faire", logo: "/set-logos/darkmoon.svg" },
  { name: "Forged in the Barrens", logo: "/set-logos/barrens.svg" },
  { name: "Legacy", logo: "/set-logos/legacy.svg" },
  { name: "Core", logo: "/set-logos/core.svg" },
  { name: "United in Stormwind", logo: "/set-logos/stormwind.svg" },
  { name: "Fractured in Alterac Valley", logo: "/set-logos/alteract.svg" },
  { name: "Voyage to the Sunken City", logo: "/set-logos/voyage.svg" },
  { name: "Murder at Castle Nathria", logo: "/set-logos/nathria.svg" },
  { name: "March of the Lich King", logo: "set-logos/lich_king.svg" },
];
